services:
  postgres:
    image: postgres
    restart: always
    env_file:
        - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-}
      - POSTGRES_USER=${POSTGRES_USER:-username}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_PORT=${POSTGRES_PORT:-5433}
      - POSTGRES_NAME=${POSTGRES_NAME:-mydb}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres: